---
#mysql installation
  - name: Install mariadb-server
    apt: name=mariadb-server state=present
 
  - name: Install python-mysqldb
    apt: name=python-mysqldb state=present

  - name: Configure mysql my.cnf
    template:  src=my.cnf dest=/etc/mysql/my.cnf

  - name: update mysql root password for all root accounts
    mysql_user:
      name: root
      login_host: localhost
      password: "{{ mysqlRootPassword }}"

  - name: copy .my.cnf file with root password credentials
    template:
      src: .my.cnf
      dest: /root/.my.cnf
      owner: root
      group: root
      mode: 0600

  - name: Restart mysql service
    service: name=mysql state=restarted
  
